const recipes = [
  {
    id: 716429,
    title: "Pasta with Garlic, Scallions, Cauliflower & Breadcrumbs",
    calories: 584,
    carbs: 45,
    fat: 20,
    image: "https://spoonacular.com/recipeImages/716429-312x231.jpg",
    imageType: "jpg",
    protein: 19,
    user: "user",
    steps: ["step1", "step2", "step3", "step4"],
  },
  {
    id: 1234,
    title: "Cauliflower fritters,besan",
    calories: 324,
    carbs: 45,
    fat: 20,
    image: "https://spoonacular.com/recipeImages/716429-312x231.jpg",
    imageType: "jpg",
    protein: 19,
    user: "user",
    steps: ["step1", "step2", "step3", "step4"],
  },
];
